[package]
name = "migration"
version = "1.0.0-beta4"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
password-auth = "1.0.0"
tokio = { version = "1.44", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.11.0", features = ["v4", "serde"] }
service = { path = "../service" }
entity = { path = "../entity" }
entity_api = { path = "../entity_api" }

[dependencies.sea-orm-migration]
version = "2.0.3"
features = ["runtime-tokio-rustls", "sqlx-postgres"]
