#######################################################
# Docker compose override file for staging environment
#######################################################
services:
  postgres:
    image: postgres:17                      # official Postgres 17 image
    container_name: postgres                # fixed name for easier links
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_OPTIONS: ${POSTGRES_OPTIONS}
    restart: unless-stopped                 # auto-restart unless stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # persist data
    networks:
      - backend_network
    healthcheck:                            # wait until DB is ready
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    depends_on:
      postgres:
        condition: service_healthy          # start after DB is healthy

volumes:
  postgres_data:                            # named volume for PG data