use crate::error::Error;
use entity::{
    cost_metric::Metric,
    pipeline_provider::Provider,
    platform_cost_metrics::{ActiveModel, Column, Entity, Model},
    Id,
};
use sea_orm::{
    prelude::Decimal, ActiveModelTrait, ActiveValue::Set, ColumnTrait, DatabaseConnection,
    EntityTrait, Order, QueryFilter, QueryOrder,
};

/// Caller-supplied fields for a new cost metric row. `id` and `created_at` are
/// generated by [`create`], so callers never provide them.
pub struct CreateParams {
    pub provider: Provider,
    pub metric: Metric,
    pub coaching_session_id: Option<Id>,
    pub source_record_id: Id,
    pub cost_low: Decimal,
    pub cost_high: Decimal,
    pub cost_avg: Decimal,
}

pub async fn create(db: &DatabaseConnection, params: CreateParams) -> Result<Model, Error> {
    let active_model = ActiveModel {
        // `id` and `created_at` are generated here so this is their single source.
        id: Set(Id::new_v4()),
        created_at: Set(chrono::Utc::now().fixed_offset()),
        provider: Set(params.provider),
        metric: Set(params.metric),
        coaching_session_id: Set(params.coaching_session_id),
        source_record_id: Set(params.source_record_id),
        cost_low: Set(params.cost_low),
        cost_high: Set(params.cost_high),
        cost_avg: Set(params.cost_avg),
    };

    Ok(active_model.insert(db).await?)
}

pub async fn find_by_session(
    db: &DatabaseConnection,
    coaching_session_id: Id,
) -> Result<Vec<Model>, Error> {
    Ok(Entity::find()
        .filter(Column::CoachingSessionId.eq(coaching_session_id))
        .order_by(Column::CreatedAt, Order::Asc)
        .all(db)
        .await?)
}

#[cfg(test)]
#[cfg(feature = "mock")]
mod tests {
    use super::*;
    use sea_orm::prelude::Decimal;
    use sea_orm::{DatabaseBackend, MockDatabase};

    fn test_metric(session_id: Id) -> Model {
        Model {
            id: Id::new_v4(),
            provider: Provider::RecallAi,
            metric: Metric::BotMinutes,
            coaching_session_id: Some(session_id),
            source_record_id: Id::new_v4(),
            cost_low: Decimal::new(10, 2),
            cost_high: Decimal::new(50, 2),
            cost_avg: Decimal::new(30, 2),
            created_at: chrono::Utc::now().fixed_offset(),
        }
    }

    fn test_params(session_id: Id) -> CreateParams {
        CreateParams {
            provider: Provider::RecallAi,
            metric: Metric::BotMinutes,
            coaching_session_id: Some(session_id),
            source_record_id: Id::new_v4(),
            cost_low: Decimal::new(10, 2),
            cost_high: Decimal::new(50, 2),
            cost_avg: Decimal::new(30, 2),
        }
    }

    #[tokio::test]
    async fn create_returns_new_cost_metric() -> Result<(), Error> {
        let session_id = Id::new_v4();
        let params = test_params(session_id);
        let returned = test_metric(session_id);
        let db = MockDatabase::new(DatabaseBackend::Postgres)
            .append_query_results(vec![vec![returned.clone()]])
            .into_connection();

        let result = create(&db, params).await?;

        assert_eq!(result.coaching_session_id, returned.coaching_session_id);
        assert_eq!(result.provider, returned.provider);
        assert_eq!(result.metric, returned.metric);
        Ok(())
    }

    #[tokio::test]
    async fn find_by_session_returns_metrics_for_session() -> Result<(), Error> {
        let session_id = Id::new_v4();
        let m1 = test_metric(session_id);
        let m2 = test_metric(session_id);
        let db = MockDatabase::new(DatabaseBackend::Postgres)
            .append_query_results(vec![vec![m1.clone(), m2.clone()]])
            .into_connection();

        let result = find_by_session(&db, session_id).await?;

        assert_eq!(result.len(), 2);
        Ok(())
    }

    #[tokio::test]
    async fn find_by_session_returns_empty_when_none_exist() -> Result<(), Error> {
        let db = MockDatabase::new(DatabaseBackend::Postgres)
            .append_query_results::<Model, Vec<Model>, _>(vec![vec![]])
            .into_connection();

        let result = find_by_session(&db, Id::new_v4()).await?;

        assert!(result.is_empty());
        Ok(())
    }
}
