//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use crate::{status, Id};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(schema_name = "refactor_platform", table_name = "actions")]
pub struct Model {
    #[serde(skip_deserializing)]
    #[sea_orm(primary_key)]
    pub id: Id,
    pub coaching_session_id: Id,
    pub goal_id: Option<Id>,
    #[serde(skip_deserializing)]
    pub user_id: Id,
    pub body: Option<String>,
    pub due_by: Option<DateTimeWithTimeZone>,
    pub status: status::Status,
    #[serde(skip_deserializing)]
    pub status_changed_at: DateTimeWithTimeZone,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub created_at: DateTimeWithTimeZone,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub updated_at: DateTimeWithTimeZone,
    #[serde(skip)]
    #[sea_orm(has_many, relation_enum = "ActionsUsers")]
    pub actions_users: HasMany<super::actions_users::Entity>,
    #[serde(skip)]
    #[sea_orm(
        belongs_to,
        relation_enum = "CoachingSessions",
        from = "coaching_session_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub coaching_session: BelongsTo<super::coaching_sessions::Entity>,
    #[serde(skip)]
    #[sea_orm(
        belongs_to,
        relation_enum = "Goals",
        from = "goal_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub goal: BelongsTo<Option<super::goals::Entity>>,
    #[serde(skip)]
    #[sea_orm(
        belongs_to,
        relation_enum = "Users",
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user: BelongsTo<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
