//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use crate::meeting_provider::Provider;
use crate::Id;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[schema(as = domain::coaching_sessions::Model)]
#[sea_orm(schema_name = "refactor_platform", table_name = "coaching_sessions")]
pub struct Model {
    #[serde(skip_deserializing)]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Id,
    pub coaching_relationship_id: Id,
    pub coaching_session_series_id: Option<Id>,
    #[serde(skip_deserializing)]
    pub ical_sequence: i32,
    /// RFC 5545 `RECURRENCE-ID`: this occurrence's original start, naive UTC like
    /// `date`. `None` for standalone sessions; never rewritten once set.
    #[serde(skip_deserializing)]
    pub ical_recurrence_id: Option<DateTime>,
    #[serde(skip_deserializing)]
    pub collab_document_name: Option<String>,
    pub date: DateTime,
    /// Session duration in minutes. Validated `1..=480` via
    /// `entity::duration::Duration` on every write.
    pub duration_minutes: i16,
    /// Optional human-authored title. Accepted on writes; `null` when unset.
    pub title: Option<String>,
    pub meeting_url: Option<String>,
    pub provider: Option<Provider>,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub created_at: DateTimeWithTimeZone,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub updated_at: DateTimeWithTimeZone,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub hydrated_at: Option<DateTimeWithTimeZone>,
    /// When the participants were last told this start: at booking, then on every
    /// reschedule whose email actually went out. The reminder sweep measures notice from
    /// here, so a session moved to less than the lead away is not reminded about. An
    /// undelivered reschedule leaves it alone, since the alternative is a coachee who
    /// gets neither the email nor the reminder.
    #[serde(skip_deserializing)]
    pub notice_given_at: DateTimeWithTimeZone,
    #[serde(skip)]
    #[sea_orm(has_many, relation_enum = "Actions")]
    pub actions: HasMany<super::actions::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many, relation_enum = "Agreements")]
    pub agreements: HasMany<super::agreements::Entity>,
    #[serde(skip)]
    #[sea_orm(
        belongs_to,
        relation_enum = "CoachingRelationships",
        from = "coaching_relationship_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub coaching_relationship: BelongsTo<super::coaching_relationships::Entity>,
    #[serde(skip)]
    #[sea_orm(
        belongs_to,
        relation_enum = "CoachingSessionSeries",
        from = "coaching_session_series_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub coaching_session_series: BelongsTo<Option<super::coaching_session_series::Entity>>,
    #[serde(skip)]
    #[sea_orm(has_many, relation_enum = "Notes")]
    pub notes: HasMany<super::notes::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many, relation_enum = "CoachingSessionTopics")]
    pub coaching_session_topics: HasMany<super::coaching_session_topics::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many, relation_enum = "Goals")]
    pub goals: HasMany<super::goals::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many, relation_enum = "CoachingSessionsGoals")]
    pub coaching_sessions_goals: HasMany<super::coaching_sessions_goals::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
