//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use crate::roles::Role;
use crate::users;
use crate::Id;
use sea_orm::entity::prelude::*;
use sea_orm::Condition;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[schema(as = entity::coaching_relationships::Model)] // OpenAPI schema
#[sea_orm(
    schema_name = "refactor_platform",
    table_name = "coaching_relationships"
)]
pub struct Model {
    #[serde(skip_deserializing)]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Id,
    #[serde(skip_deserializing)]
    pub organization_id: Id,
    pub coach_id: Id,
    pub coachee_id: Id,
    #[serde(skip_deserializing)]
    // TODO we need to make sure this is unique in the scope of an organization_id.
    // I did some research and there are two ways to do this:
    // 1. Create a unique constraint at the database level.
    // 2. Add application logic (probably in entity_api) to make the check.
    // We'll need to add a migration for that eventually.
    pub slug: String,

    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub created_at: DateTimeWithTimeZone,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub updated_at: DateTimeWithTimeZone,
    #[serde(skip)]
    #[sea_orm(
        belongs_to,
        relation_enum = "Organizations",
        from = "organization_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub organization: BelongsTo<super::organizations::Entity>,
    #[serde(skip)]
    #[sea_orm(
        belongs_to,
        relation_enum = "Coaches",
        from = "coach_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub coach: BelongsTo<super::coaches::Entity>,
    #[serde(skip)]
    #[sea_orm(
        belongs_to,
        relation_enum = "Coachees",
        from = "coachee_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub coachee: BelongsTo<super::coachees::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many, relation_enum = "Goals")]
    pub goals: HasMany<super::goals::Entity>,
}

impl Model {
    /// Returns `true` if the given user is a participant (coach or coachee)
    /// in this coaching relationship.
    pub fn includes_user(&self, user_id: Id) -> bool {
        self.coach_id == user_id || self.coachee_id == user_id
    }

    /// Returns `true` if the given user may access this relationship's data.
    ///
    /// Requires participation *and* current membership of the relationship's
    /// organization, so a user removed from the organization loses access to
    /// coaching history they took part in. A global SuperAdmin participant keeps
    /// access without holding an organization role.
    pub fn grants_access_to(&self, user: &users::Model) -> bool {
        self.includes_user(user.id)
            && user.roles.iter().any(|role| {
                role.organization_id == Some(self.organization_id)
                    || (role.role == Role::SuperAdmin && role.organization_id.is_none())
            })
    }
}

/// A caller's visibility scope, derived once per request from their preloaded
/// roles (see `domain::search::scope_for`). Input to [`visible_to`], the
/// corpus-wide query form of [`Model::grants_access_to`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Scope {
    pub user_id: Id,
    /// SuperAdmin role with `organization_id` NULL — sees everything.
    pub is_super_admin: bool,
    /// Organizations where the caller holds the `Admin` role.
    pub admin_org_ids: Vec<Id>,
    /// Every organization the caller holds any role in.
    pub member_org_ids: Vec<Id>,
}

/// The query form of [`Model::grants_access_to`]: a `Condition` selecting every
/// coaching relationship the caller may access, evaluated corpus-wide.
///
/// Tier 1 mirrors `grants_access_to` exactly — participant (coach or coachee)
/// AND current member of the relationship's organization. Tier 2 adds every
/// relationship in orgs where the caller is an Admin. Super admins skip this
/// condition entirely (callers must not apply it when `scope.is_super_admin`).
///
/// Kept beside `grants_access_to` deliberately: these are the two expressions
/// of one rule, and a DB-backed equivalence test pins them together. Change one,
/// mirror the other.
pub fn visible_to(scope: &Scope) -> Condition {
    Condition::any()
        .add(
            Condition::all()
                .add(
                    Column::CoachId
                        .eq(scope.user_id)
                        .or(Column::CoacheeId.eq(scope.user_id)),
                )
                .add(Column::OrganizationId.is_in(scope.member_org_ids.iter().copied())),
        )
        .add(Column::OrganizationId.is_in(scope.admin_org_ids.iter().copied()))
}

impl ActiveModelBehavior for ActiveModel {}

// Alias to be used with queries
#[derive(DeriveIden, Clone, Copy)]
pub struct RelationshipAsCoach;

// Alias to be used with queries
#[derive(DeriveIden, Clone, Copy)]
pub struct RelationshipAsCoachee;

#[cfg(test)]
#[path = "coaching_relationships_access_tests.rs"]
mod access_tests;

#[cfg(test)]
mod tests {
    use super::*;

    fn create_test_relationship(coach_id: Id, coachee_id: Id) -> Model {
        let now = chrono::Utc::now().fixed_offset();
        Model {
            id: Id::new_v4(),
            organization_id: Id::new_v4(),
            coach_id,
            coachee_id,
            slug: "test-slug".to_string(),
            created_at: now,
            updated_at: now,
        }
    }

    #[test]
    fn includes_user_returns_true_for_coach() {
        let coach_id = Id::new_v4();
        let coachee_id = Id::new_v4();
        let relationship = create_test_relationship(coach_id, coachee_id);

        assert!(relationship.includes_user(coach_id));
    }

    #[test]
    fn includes_user_returns_true_for_coachee() {
        let coach_id = Id::new_v4();
        let coachee_id = Id::new_v4();
        let relationship = create_test_relationship(coach_id, coachee_id);

        assert!(relationship.includes_user(coachee_id));
    }

    #[test]
    fn includes_user_returns_false_for_unrelated_user() {
        let coach_id = Id::new_v4();
        let coachee_id = Id::new_v4();
        let other_user_id = Id::new_v4();
        let relationship = create_test_relationship(coach_id, coachee_id);

        assert!(!relationship.includes_user(other_user_id));
    }
}
