//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use crate::meeting_provider::Provider;
use crate::Id;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[schema(as = domain::coaching_sessions::Model)]
#[sea_orm(schema_name = "refactor_platform", table_name = "coaching_sessions")]
pub struct Model {
    #[serde(skip_deserializing)]
    #[sea_orm(primary_key)]
    pub id: Id,
    pub coaching_relationship_id: Id,
    pub coaching_session_series_id: Option<Id>,
    #[serde(skip_deserializing)]
    pub ical_sequence: i32,
    /// RFC 5545 `RECURRENCE-ID`: this occurrence's original start, naive UTC like
    /// `date`. `None` for standalone sessions; never rewritten once set.
    #[serde(skip_deserializing)]
    pub ical_recurrence_id: Option<DateTime>,
    #[serde(skip_deserializing)]
    pub collab_document_name: Option<String>,
    pub date: DateTime,
    /// Session duration in minutes. Validated `1..=480` via
    /// `entity::duration::Duration` on every write.
    pub duration_minutes: i16,
    /// Optional human-authored title. Accepted on writes; `null` when unset.
    pub title: Option<String>,
    pub meeting_url: Option<String>,
    pub provider: Option<Provider>,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub created_at: DateTimeWithTimeZone,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub updated_at: DateTimeWithTimeZone,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub hydrated_at: Option<DateTimeWithTimeZone>,
    /// The `date` value the 24-hour reminder was last sent for, naive UTC like `date`.
    /// `None` means no reminder has gone out. Holding the start rather than a "sent at"
    /// timestamp is what makes a reschedule re-arm the reminder: the sweep claims rows
    /// where this `IS DISTINCT FROM date`, so moving a session automatically makes it
    /// due again with no other code path having to clear the flag.
    #[serde(skip_deserializing)]
    pub reminder_sent_for_start: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::actions::Entity")]
    Actions,
    #[sea_orm(has_many = "super::agreements::Entity")]
    Agreements,
    #[sea_orm(
        belongs_to = "super::coaching_relationships::Entity",
        from = "Column::CoachingRelationshipId",
        to = "super::coaching_relationships::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CoachingRelationships,
    #[sea_orm(
        belongs_to = "super::coaching_session_series::Entity",
        from = "Column::CoachingSessionSeriesId",
        to = "super::coaching_session_series::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    CoachingSessionSeries,
    #[sea_orm(has_many = "super::notes::Entity")]
    Notes,
    #[sea_orm(has_many = "super::coaching_session_topics::Entity")]
    CoachingSessionTopics,
    #[sea_orm(has_many = "super::goals::Entity")]
    Goals,
    #[sea_orm(has_many = "super::coaching_sessions_goals::Entity")]
    CoachingSessionsGoals,
}

impl Related<super::actions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Actions.def()
    }
}

impl Related<super::agreements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agreements.def()
    }
}

impl Related<super::coaching_relationships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoachingRelationships.def()
    }
}

impl Related<super::coaching_session_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoachingSessionSeries.def()
    }
}

impl Related<super::notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notes.def()
    }
}

impl Related<super::coaching_session_topics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoachingSessionTopics.def()
    }
}

impl Related<super::goals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Goals.def()
    }
}

impl Related<super::coaching_sessions_goals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoachingSessionsGoals.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
