//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use crate::status::Status;
use crate::Id;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[schema(as = entity::goals::Model)]
#[sea_orm(schema_name = "refactor_platform", table_name = "goals")]
pub struct Model {
    #[serde(skip_deserializing)]
    #[sea_orm(primary_key)]
    pub id: Id,
    pub coaching_relationship_id: Id,
    pub created_in_session_id: Option<Id>,
    #[serde(skip_deserializing)]
    pub user_id: Id,
    pub title: Option<String>,
    pub body: Option<String>,
    pub status: Status,
    #[serde(skip_deserializing)]
    pub status_changed_at: Option<DateTimeWithTimeZone>,
    #[serde(skip_deserializing)]
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub target_date: Option<Date>,
    #[serde(skip_deserializing)]
    pub created_at: DateTimeWithTimeZone,
    #[serde(skip_deserializing)]
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::coaching_relationships::Entity",
        from = "Column::CoachingRelationshipId",
        to = "super::coaching_relationships::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    CoachingRelationships,
    #[sea_orm(
        belongs_to = "super::coaching_sessions::Entity",
        from = "Column::CreatedInSessionId",
        to = "super::coaching_sessions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CoachingSessions,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::coaching_relationships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoachingRelationships.def()
    }
}

impl Related<super::coaching_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoachingSessions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Model {
    /// Returns `true` if this goal has `InProgress` status.
    pub fn in_progress(&self) -> bool {
        self.status == Status::InProgress
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    fn create_test_goal(status: Status) -> Model {
        let now = chrono::Utc::now().fixed_offset();
        Model {
            id: Id::new_v4(),
            coaching_relationship_id: Id::new_v4(),
            created_in_session_id: None,
            user_id: Id::new_v4(),
            title: Some("Test goal".to_string()),
            body: None,
            status,
            status_changed_at: None,
            completed_at: None,
            target_date: None,
            created_at: now,
            updated_at: now,
        }
    }

    #[test]
    fn in_progress_returns_false_for_not_started() {
        assert!(!create_test_goal(Status::NotStarted).in_progress());
    }

    #[test]
    fn in_progress_returns_true_for_in_progress() {
        assert!(create_test_goal(Status::InProgress).in_progress());
    }

    #[test]
    fn in_progress_returns_false_for_completed() {
        assert!(!create_test_goal(Status::Completed).in_progress());
    }

    #[test]
    fn in_progress_returns_false_for_wont_do() {
        assert!(!create_test_goal(Status::WontDo).in_progress());
    }
}
