//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use crate::status::Status;
use crate::Id;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[schema(as = entity::goals::Model)]
#[sea_orm(schema_name = "refactor_platform", table_name = "goals")]
pub struct Model {
    #[serde(skip_deserializing)]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Id,
    pub coaching_relationship_id: Id,
    pub created_in_session_id: Option<Id>,
    #[serde(skip_deserializing)]
    pub user_id: Id,
    pub title: Option<String>,
    pub body: Option<String>,
    pub status: Status,
    #[serde(skip_deserializing)]
    pub status_changed_at: Option<DateTimeWithTimeZone>,
    #[serde(skip_deserializing)]
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub target_date: Option<Date>,
    #[serde(skip_deserializing)]
    pub created_at: DateTimeWithTimeZone,
    #[serde(skip_deserializing)]
    pub updated_at: DateTimeWithTimeZone,
    #[serde(skip)]
    #[sea_orm(
        belongs_to,
        relation_enum = "CoachingRelationships",
        from = "coaching_relationship_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub coaching_relationship: BelongsTo<super::coaching_relationships::Entity>,
    #[serde(skip)]
    #[sea_orm(
        belongs_to,
        relation_enum = "CoachingSessions",
        from = "created_in_session_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub created_in_session: BelongsTo<Option<super::coaching_sessions::Entity>>,
    #[serde(skip)]
    #[sea_orm(
        belongs_to,
        relation_enum = "Users",
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user: BelongsTo<super::users::Entity>,
}

impl Model {
    /// Returns `true` if this goal has `InProgress` status.
    pub fn in_progress(&self) -> bool {
        self.status == Status::InProgress
    }

    /// Returns `true` if this goal is in a completed status (`Completed` or `WontDo`).
    pub fn is_completed(&self) -> bool {
        self.status.is_completed()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    fn create_test_goal(status: Status) -> Model {
        let now = chrono::Utc::now().fixed_offset();
        Model {
            id: Id::new_v4(),
            coaching_relationship_id: Id::new_v4(),
            created_in_session_id: None,
            user_id: Id::new_v4(),
            title: Some("Test goal".to_string()),
            body: None,
            status,
            status_changed_at: None,
            completed_at: None,
            target_date: None,
            created_at: now,
            updated_at: now,
        }
    }

    #[test]
    fn in_progress_returns_false_for_not_started() {
        assert!(!create_test_goal(Status::NotStarted).in_progress());
    }

    #[test]
    fn in_progress_returns_true_for_in_progress() {
        assert!(create_test_goal(Status::InProgress).in_progress());
    }

    #[test]
    fn in_progress_returns_false_for_completed() {
        assert!(!create_test_goal(Status::Completed).in_progress());
    }

    #[test]
    fn in_progress_returns_false_for_wont_do() {
        assert!(!create_test_goal(Status::WontDo).in_progress());
    }

    #[test]
    fn is_completed_returns_true_for_completed_status() {
        assert!(create_test_goal(Status::Completed).is_completed());
    }

    #[test]
    fn is_completed_returns_true_for_wont_do_status() {
        assert!(create_test_goal(Status::WontDo).is_completed());
    }

    #[test]
    fn is_completed_returns_false_for_not_started() {
        assert!(!create_test_goal(Status::NotStarted).is_completed());
    }

    #[test]
    fn is_completed_returns_false_for_in_progress() {
        assert!(!create_test_goal(Status::InProgress).is_completed());
    }

    #[test]
    fn is_completed_returns_false_for_on_hold() {
        assert!(!create_test_goal(Status::OnHold).is_completed());
    }
}
