//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use crate::Id;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, ToSchema, Serialize, Deserialize)]
#[schema(as = entity::organizations::Model)] // OpenAPI schema
#[sea_orm(schema_name = "refactor_platform", table_name = "organizations")]
pub struct Model {
    #[serde(skip_deserializing)]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Id,
    #[sea_orm(unique)]
    pub name: String,
    pub logo: Option<String>,
    #[serde(skip_deserializing)]
    #[sea_orm(unique)]
    pub slug: String,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub created_at: DateTimeWithTimeZone,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub updated_at: DateTimeWithTimeZone,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)]
    pub archived_at: Option<DateTimeWithTimeZone>,
    #[serde(skip_deserializing)]
    pub archived_by: Option<Id>,
    #[serde(skip)]
    #[sea_orm(has_many, relation_enum = "CoachingRelationships")]
    pub coaching_relationships: HasMany<super::coaching_relationships::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many, relation_enum = "UserRoles")]
    pub user_roles: HasMany<super::user_roles::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many, via = "coaching_relationships::Organizations")]
    pub coaches: HasMany<super::coaches::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many, via = "coaching_relationships::Organizations")]
    pub coachees: HasMany<super::coachees::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many, via = "user_roles::Organizations")]
    pub users: HasMany<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
