//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub use crate::roles::Role;
use crate::user_invite_status::InviteStatus;
use crate::Id;
use axum_login::AuthUser;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

fn default_timezone() -> String {
    "UTC".to_string()
}

// TODO: We should find a way to centralize the users/coaches/coachees types
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, ToSchema, Serialize, Deserialize)]
#[schema(as = domain::users::Model)] // OpenAPI schema
#[sea_orm(schema_name = "refactor_platform", table_name = "users")]
pub struct Model {
    #[serde(skip_deserializing)]
    #[sea_orm(primary_key)]
    pub id: Id,
    #[sea_orm(unique)]
    pub email: String,
    pub first_name: String,
    pub last_name: String,
    pub display_name: Option<String>,
    #[serde(skip_serializing)]
    pub password: Option<String>,
    pub github_username: Option<String>,
    pub github_profile_url: Option<String>,
    // Serde default mirrors the column's `DEFAULT 'UTC'` so it's optional on the wire.
    #[sea_orm(default = "UTC")]
    #[serde(default = "default_timezone")]
    pub timezone: String,
    /// Per-coach default session duration in minutes. Validated `1..=480`
    /// via `entity::duration::Duration`. Serde default mirrors the column's
    /// `NOT NULL DEFAULT 60` so it's optional on the wire (not an invalid `0`).
    #[serde(default = "crate::duration::Duration::default_minutes")]
    pub default_coaching_session_duration_minutes: i16,
    #[sea_orm(default = "user")]
    // This is a legacy field and will be removed in favor of roles
    #[serde(skip_deserializing)]
    pub role: Role,
    /// Associated user roles (populated via find_with_related)
    /// This field is ignored by SeaORM for database operations.
    #[sea_orm(ignore)]
    #[serde(skip_deserializing)]
    pub roles: Vec<super::user_roles::Model>,
    /// Computed at query time based on password presence and magic link token state.
    /// `None` when not computed (e.g. login, profile fetch).
    #[sea_orm(ignore)]
    #[serde(skip_deserializing, skip_serializing_if = "Option::is_none")]
    pub invite_status: Option<InviteStatus>,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub created_at: DateTimeWithTimeZone,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_roles::Entity")]
    UserRoles,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_roles::Relation::Organizations.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::user_roles::Relation::Users.def().rev())
    }
}

impl Related<super::user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl AuthUser for Model {
    type Id = crate::Id;

    fn id(&self) -> Self::Id {
        self.id
    }

    fn session_auth_hash(&self) -> &[u8] {
        self.password
            .as_deref()
            .map(|p| p.as_bytes())
            .unwrap_or_else(|| self.id.as_bytes())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;
    use uuid::Uuid;

    fn test_user(id: Uuid, password: Option<&str>) -> Model {
        Model {
            id,
            email: "test@example.com".into(),
            first_name: "Test".into(),
            last_name: "User".into(),
            display_name: None,
            password: password.map(String::from),
            github_username: None,
            github_profile_url: None,
            timezone: "UTC".into(),
            default_coaching_session_duration_minutes: crate::duration::Duration::default_minutes(),
            role: Role::default(),
            roles: vec![],
            invite_status: None,
            created_at: Utc::now().into(),
            updated_at: Utc::now().into(),
        }
    }

    #[test]
    fn session_auth_hash_uses_password_when_present() {
        let user = test_user(Uuid::new_v4(), Some("hash123"));
        assert_eq!(user.session_auth_hash(), b"hash123");
    }

    #[test]
    fn session_auth_hash_falls_back_to_uuid_when_no_password() {
        let id = Uuid::new_v4();
        let user = test_user(id, None);
        assert_eq!(user.session_auth_hash(), id.as_bytes());
    }

    #[test]
    fn session_auth_hash_differs_for_distinct_passwordless_users() {
        let user_a = test_user(Uuid::new_v4(), None);
        let user_b = test_user(Uuid::new_v4(), None);
        assert_ne!(user_a.session_auth_hash(), user_b.session_auth_hash());
    }

    /// Magic-link invite path: payload omits duration AND timezone.
    /// Both must default (60 / "UTC"), not 422.
    #[test]
    fn deserialize_defaults_duration_and_timezone_when_omitted() {
        let model: Model = serde_json::from_value(serde_json::json!({
            "email": "invite@example.com",
            "first_name": "Inv",
            "last_name": "Ite",
            "display_name": "Inv Ite",
        }))
        .expect("invite payload without duration/timezone must deserialize");
        assert_eq!(
            model.default_coaching_session_duration_minutes,
            crate::duration::Duration::default_minutes(),
        );
        assert_eq!(model.timezone, "UTC");
    }

    /// Explicit duration is still honored.
    #[test]
    fn deserialize_honors_explicit_duration() {
        let model: Model = serde_json::from_value(serde_json::json!({
            "email": "coach@example.com",
            "first_name": "Co",
            "last_name": "Ach",
            "timezone": "America/New_York",
            "default_coaching_session_duration_minutes": 90,
        }))
        .expect("payload with duration must deserialize");
        assert_eq!(model.default_coaching_session_duration_minutes, 90);
    }
}
