//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub use crate::roles::Role;
use crate::user_invite_status::InviteStatus;
use crate::Id;
use axum_login::AuthUser;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

// TODO: We should find a way to centralize the users/coaches/coachees types
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, ToSchema, Serialize, Deserialize)]
#[schema(as = domain::users::Model)] // OpenAPI schema
#[sea_orm(schema_name = "refactor_platform", table_name = "users")]
pub struct Model {
    #[serde(skip_deserializing)]
    #[sea_orm(primary_key)]
    pub id: Id,
    #[sea_orm(unique)]
    pub email: String,
    pub first_name: String,
    pub last_name: String,
    pub display_name: Option<String>,
    #[serde(skip_serializing)]
    pub password: Option<String>,
    pub github_username: Option<String>,
    pub github_profile_url: Option<String>,
    #[sea_orm(default = "UTC")]
    pub timezone: String,
    #[sea_orm(default = "user")]
    // This is a legacy field and will be removed in favor of roles
    #[serde(skip_deserializing)]
    pub role: Role,
    /// Associated user roles (populated via find_with_related)
    /// This field is ignored by SeaORM for database operations.
    #[sea_orm(ignore)]
    #[serde(skip_deserializing)]
    pub roles: Vec<super::user_roles::Model>,
    /// Computed at query time based on password presence and magic link token state.
    /// `None` when not computed (e.g. login, profile fetch).
    #[sea_orm(ignore)]
    #[serde(skip_deserializing, skip_serializing_if = "Option::is_none")]
    pub invite_status: Option<InviteStatus>,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub created_at: DateTimeWithTimeZone,
    #[serde(skip_deserializing)]
    #[schema(value_type = String, format = DateTime)] // Applies to OpenAPI schema
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_roles::Entity")]
    UserRoles,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_roles::Relation::Organizations.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::user_roles::Relation::Users.def().rev())
    }
}

impl Related<super::user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl AuthUser for Model {
    type Id = crate::Id;

    fn id(&self) -> Self::Id {
        self.id
    }

    fn session_auth_hash(&self) -> &[u8] {
        self.password
            .as_deref()
            .map(|p| p.as_bytes())
            .unwrap_or_else(|| self.id.as_bytes())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;
    use uuid::Uuid;

    fn test_user(id: Uuid, password: Option<&str>) -> Model {
        Model {
            id,
            email: "test@example.com".into(),
            first_name: "Test".into(),
            last_name: "User".into(),
            display_name: None,
            password: password.map(String::from),
            github_username: None,
            github_profile_url: None,
            timezone: "UTC".into(),
            role: Role::default(),
            roles: vec![],
            created_at: Utc::now().into(),
            updated_at: Utc::now().into(),
        }
    }

    #[test]
    fn session_auth_hash_uses_password_when_present() {
        let user = test_user(Uuid::new_v4(), Some("hash123"));
        assert_eq!(user.session_auth_hash(), b"hash123");
    }

    #[test]
    fn session_auth_hash_falls_back_to_uuid_when_no_password() {
        let id = Uuid::new_v4();
        let user = test_user(id, None);
        assert_eq!(user.session_auth_hash(), id.as_bytes());
    }

    #[test]
    fn session_auth_hash_differs_for_distinct_passwordless_users() {
        let user_a = test_user(Uuid::new_v4(), None);
        let user_b = test_user(Uuid::new_v4(), None);
        assert_ne!(user_a.session_auth_hash(), user_b.session_auth_hash());
    }
}
