[package]
name = "web"
version = "1.0.0-beta1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = { path = "../domain" }
service = { path = "../service" }
entity_api = { path = "../entity_api" }

<<<<<<< HEAD
axum = "0.8.1"
axum-login = "0.17.0"
=======
axum = "0.7.7"
axum-login = "0.16.0"
chrono = { version = "0.4.38", features = ["serde"] }
>>>>>>> f61c08b (merges remaining changes from main.)
log = "0.4.22"
tower-http = { version = "0.6.1", features = ["fs", "cors"] }
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
sqlx = { version = "0.8.3", features = ["time", "runtime-tokio"] }
tokio = { version = "1.40", features = [
    "full",
] } # Remove the ".0" for consistency
tower = { version = "0.5.1", features = ["util", "http"] } # or similar
tower-sessions = { version = "0.14.0" }
tower-sessions-sqlx-store = { version = "0.15.0", features = ["postgres"] }
time = "0.3.36"
utoipa = { version = "5.3.1", features = ["axum_extras", "uuid"] }
utoipa-rapidoc = { version = "6.0.0", features = ["axum"] }

[dependencies.sea-orm]
version = "1.1.0" # sea-orm version
features = [
    "debug-print",
    "runtime-tokio-native-tls",
    "sea-orm-internal",
    "sqlx-postgres",
    "with-uuid",
]

[features]
mock = ["sea-orm/mock"]

[dev-dependencies]
anyhow = "1.0.89"
chrono = { version = "0.4.38", features = ["serde"] }
password-auth = "1.0.0"
reqwest = { version = "0.12.12", features = ["json", "cookies"] }
